### ISSUE TITLE
Measures constant noise regardless of configuration

### ISSUE THREAD

**Issue by RoFree** [JosephEoff/Rodriguez#2]
This is a great project!
I've been trying to build my own curve tracer but I'm running into an issue where the curve tracer is only detecting this odd periodic noise regardless of whether or not there is a device. I attached a screenshot for reference. 
Do you have any idea what might be causing this? I've checked all the circuit connections and for reference I'm using an Adafruit Metro (Atmega328) and I've put together the circuit using discretes on a breadboard. I've been beating my head against the problem for a week and I'm wondering if it is a problem you came across when designing Rodriguez.

Some more version information:
I'm using the latest packaged windows executable from the releases (v1.0) and the most recent arduino code (As of 5/31/2021).

![pasted image 0 (1)](https://user-images.githubusercontent.com/47285106/120263539-bb458600-c250-11eb-9394-be3b416bb67d.png)

**Comment by JosephEoff** [comment]
Hello, RoFree.
Your question reminds me that I haven't written any operating instructions for Rodriguez yet.

The picture shows Rodrigeuz set to do current/voltage trace for a diode.  If you have it set to the diode function but have a transistor connected then the chart would be misleading.

The lowest (red) line on a transistor trace is usually very messy.  The collector current is somewhere in the single digit microamperes - very low, and difficult to measure accurately, even with all the things Rodriguez does to make the traces smooth.

Try the following:
For a diode trace, make sure that the diode is connected in the correct direction.  Reverse it if you aren't sure.

For a transistor, select the correct device type from the dropdown box (currently set to "Diode.")  The dropdown is under the selection box for "Number of traces."

In general, you need to use very short wires for all of the connections.  You are measuring microamperes, milliamperes, and millivollts.  The resistances in the circuit are all relatively high, making it susceptible to picking up noise.

I'll see about writing up some operating instructions this evening.  It is time for me to go to work now.

**Comment by JosephEoff** [comment]
@RoFree:
I did some experiments this evening, and I can't replicate the problem.

Could you make some photos of your set up and attach them to a comment here?

I suspect there's something mis-wired on the breadboard.

**Comment by RoFree** [comment]
Of course! 
![IMG_6180-exif-remove](https://user-images.githubusercontent.com/47285106/120390551-b3cebd00-c2e2-11eb-8e3f-f9220dc07711.jpeg)
![IMG_6181-exif-remove](https://user-images.githubusercontent.com/47285106/120390557-b6c9ad80-c2e2-11eb-8932-1978275d95a8.jpeg)
![IMG_6182-exif-remove](https://user-images.githubusercontent.com/47285106/120390566-b8937100-c2e2-11eb-859c-138fe2e9b6d4.jpeg)
![IMG_6183-exif-remove](https://user-images.githubusercontent.com/47285106/120390571-ba5d3480-c2e2-11eb-82a9-f9fea5ffea88.jpeg)

**Comment by JosephEoff** [comment]
This is wrong for sure.  The red wire is not connected to the diode or to the blue wire.  The red wire is the signal that should be driving the diode.

![grafik](https://user-images.githubusercontent.com/13119635/120491793-cf58c700-c3b9-11eb-9092-b0b0659156ab.png)

**Comment by RoFree** [comment]
I changed out the connections like you recommended and got the same result. I also took a look at the output with an oscilloscope and I'm not sure low pass filter on the PWM signal is doing the right job. Is the lowpass filter a 100 ohm resistor and 10 microFarad capacitor?

**Comment by JosephEoff** [comment]
![Rodriguez-Schematic](https://user-images.githubusercontent.com/13119635/120554762-6e9dae80-c3fa-11eb-9731-1f19b4d05404.png)

There are two low pass filters.  Each is made of a 100 ohm resistor and a 10uF capacitor.

1. Double check your wiring.
2. Diodes traces are made with the output connected to D10.  You seem to be using D9.

I'll see about writing some better instructions tomorrow.

**Comment by JosephEoff** [comment]
It might help to read the blog posts I wrote while building Rodriguez.

https://josepheoff.github.io/posts/iv-1-toc

**Comment by JosephEoff** [comment]
@RoFree : 

I have extended the [Rodriguez wiki.](https://github.com/JosephEoff/Rodriguez/wiki)  Please take a look and see if the wiring diagrams and instructions help you solve your difficulties.

**Comment by JosephEoff** [comment]
@RoFree:  Have you had a chance to check things out following the instructions I posted in the wiki?

**Comment by RoFree** [comment]
Thank you so much for all your help! I haven't got it working yet. I suspect something is going wrong with the PWM voltage generation and I'm working on troubleshooting.

**Comment by JosephEoff** [comment]
@RoFree 
Did the wiring diagrams help solve your problems?

**Comment by RoFree** [comment]
Not really. I'm going to close the issue and see if I can try some things to get it working. Thanks again!
