### ISSUE TITLE
Discussion with xiaolaba

### ISSUE THREAD

**Issue by xiaolaba** [JosephEoff/Rodriguez#3]
hi, because this repo has no discussion tag, we would like post some query about the code design consideration.
there following is the raw data log for the curve tracer, used 2 traces of default, so more traces should be the same. looks like each starting of a trace and a dummy loop, for the same count of Vb setting about 510 times before VCollectorBias was commanded to ramp up, any consideration for this particular figure that and how would be determined for the loop if it is for charging time.

`
Vb = 0
000000: 0B
000001: 0	0	0	0

Vc = max
000002: 
1023C
000003: 0	0	253985	254255

Vb = 50%
000004: 
511B
000005: 96090	34691	23708	184305

Vc = 170/1023 %
000006: 
170C
000007: 121613	33940	1431	31216

Vb= 50%, loop 510 times,
000008: 
511B
000009: 122025	33910	1375	28845
000010: 
511B
000011: 122093	33903	1373	28845
000012: 
511B
000013: 122122	33899	1370	28864
000014: 
511B
000015: 122138	33905	1378	28840
000016: 
511B
000017: 122149	33908	1376	28837
000018: 
511B
000019: 122148	33903	1371	28839
000020: 
511B
000021: 122164	33906	1373	28838
000022: 
511B
000023: 122157	33902	1363	28853
000024: 
511B
000025: 122161	33898	1367	28836
000026: 
511B
000027: 122174	33904	1368	28845
000028: 
511B
000029: 122157	33905	1373	28837
000030: 
511B
000031: 122174	33899	1368	28837
000032: 
511B
000033: 122173	33896	1372	28842
000034: 
511B
000035: 122165	33902	1375	28853
000036: 
511B
000037: 122169	33899	1371	28850
000038: 
511B
000039: 122171	33903	1367	28840
000040: 
511B
000041: 122183	33903	1371	28850
000042: 
511B
000043: 122171	33904	1370	28840
000044: 
511B
000045: 122173	33905	1367	28849
000046: 
511B
000047: 122169	33904	1370	28862
000048: 
511B
000049: 122184	33899	1367	28836
000050: 
511B
000051: 122173	33905	1369	28842
000052: 
511B
000053: 122184	33902	1369	28836
000054: 
511B
000055: 122170	33906	1369	28849
000056: 
511B
000057: 122170	33902	1362	28846
000058: 
511B
000059: 122177	33899	1369	28837
000060: 
511B
000061: 122179	33899	1361	28860
000062: 
511B
000063: 122177	33894	1376	28851
000064: 
511B
000065: 122173	33900	1372	28835
000066: 
511B
000067: 122180	33898	1362	28855
000068: 
511B
000069: 122174	33899	1369	28851
000070: 
511B
000071: 122180	33897	1379	28850
000072: 
511B
000073: 122182	33899	1362	28853
000074: 
511B
000075: 122175	33906	1368	28836
000076: 
511B
000077: 122179	33894	1372	28854
000078: 
511B
000079: 122178	33895	1382	28847
000080: 
511B
000081: 122174	33891	1376	28843
000082: 
511B
000083: 122189	33904	1371	28838
000084: 
511B
000085: 122176	33895	1369	28849
000086: 
511B
000087: 122182	33892	1364	28846
000088: 
511B
000089: 122181	33898	1367	28846
000090: 
511B
000091: 122179	33901	1369	28849
000092: 
511B
000093: 122186	33901	1366	28841
000094: 
511B
000095: 122183	33899	1365	28836
000096: 
511B
000097: 122174	33903	1364	28838
000098: 
511B
000099: 122174	33893	1367	28862
000100: 
511B
000101: 122184	33896	1363	28848
000102: 
511B
000103: 122180	33890	1375	28841
000104: 
511B
000105: 122179	33898	1371	28853
000106: 
511B
000107: 122185	33907	1371	28843
000108: 
511B
000109: 122190	33899	1362	28845
000110: 
511B
000111: 122180	33902	1376	28842
000112: 
511B
000113: 122186	33903	1369	28837
000114: 
511B
000115: 122174	33901	1377	28842
000116: 
511B
000117: 122174	33898	1366	28839
000118: 
511B
000119: 122182	33899	1373	28850
000120: 
511B
000121: 122180	33903	1363	28841
000122: 
511B
000123: 122179	33896	1363	28847
000124: 
511B
000125: 122178	33896	1374	28840
000126: 
511B
000127: 122186	33896	1369	28855
000128: 
511B
000129: 122187	33902	1372	28838
000130: 
511B
000131: 122182	33899	1372	28844
000132: 
511B
000133: 122179	33897	1372	28842
000134: 
511B
000135: 122181	33896	1369	28843
000136: 
511B
000137: 122185	33893	1366	28846
000138: 
511B
000139: 122179	33888	1374	28857
000140: 
511B
000141: 122184	33897	1373	28841
000142: 
511B
000143: 122180	33890	1365	28837
000144: 
511B
000145: 122182	33894	1372	28842
000146: 
511B
000147: 122184	33901	1365	28847
000148: 
511B
000149: 122179	33894	1369	28844
000150: 
511B
000151: 122185	33889	1371	28843
000152: 
511B
000153: 122178	33895	1371	28854
000154: 
511B
000155: 122184	33898	1366	28847
000156: 
511B
000157: 122176	33896	1371	28842
000158: 
511B
000159: 122185	33896	1362	28834
000160: 
511B
000161: 122178	33894	1374	28837
000162: 
511B
000163: 122184	33900	1367	28840
000164: 
511B
000165: 122184	33901	1367	28835
000166: 
511B
000167: 122185	33893	1367	28836
000168: 
511B
000169: 122178	33895	1368	28836
000170: 
511B
000171: 122176	33892	1369	28860
000172: 
511B
000173: 122193	33889	1369	28850
000174: 
511B
000175: 122182	33899	1370	28838
000176: 
511B
000177: 122186	33889	1368	28846
000178: 
511B
000179: 122186	33891	1369	28844
000180: 
511B
000181: 122182	33894	1368	28836
000182: 
511B
000183: 122182	33897	1374	28863
000184: 
511B
000185: 122181	33892	1366	28845
000186: 
511B
000187: 122184	33895	1370	28846
000188: 
511B
000189: 122178	33891	1379	28857
000190: 
511B
000191: 122186	33890	1365	28850
000192: 
511B
000193: 122191	33894	1364	28842
000194: 
511B
000195: 122179	33893	1372	28859
000196: 
511B
000197: 122187	33887	1370	28835
000198: 
511B
000199: 122180	33889	1369	28844
000200: 
511B
000201: 122176	33888	1365	28863
000202: 
511B
000203: 122186	33890	1368	28848
000204: 
511B
000205: 122189	33894	1374	28848
000206: 
511B
000207: 122185	33890	1373	28843
000208: 
511B
000209: 122181	33889	1364	28846
000210: 
511B
000211: 122181	33876	1361	28852
000212: 
511B
000213: 122182	33887	1372	28850
000214: 
511B
000215: 122178	33881	1369	28846
000216: 
511B
000217: 122182	33890	1364	28840
000218: 
511B
000219: 122182	33883	1365	28849
000220: 
511B
000221: 122183	33882	1364	28838
000222: 
511B
000223: 122179	33885	1376	28832
000224: 
511B
000225: 122176	33883	1368	28843
000226: 
511B
000227: 122183	33885	1364	28834
000228: 
511B
000229: 122185	33883	1369	28836
000230: 
511B
000231: 122174	33884	1369	28832
000232: 
511B
000233: 122191	33884	1363	28836
000234: 
511B
000235: 122173	33878	1362	28857
000236: 
511B
000237: 122188	33880	1366	28844
000238: 
511B
000239: 122182	33875	1361	28860
000240: 
511B
000241: 122182	33881	1376	28837
000242: 
511B
000243: 122184	33872	1361	28843
000244: 
511B
000245: 122177	33879	1368	28860
000246: 
511B
000247: 122179	33872	1366	28839
000248: 
511B
000249: 122188	33880	1363	28850
000250: 
511B
000251: 122181	33881	1357	28836
000252: 
511B
000253: 122189	33881	1366	28840
000254: 
511B
000255: 122180	33874	1369	28836
000256: 
511B
000257: 122180	33876	1363	28834
000258: 
511B
000259: 122184	33883	1370	28839
000260: 
511B
000261: 122179	33871	1365	28851
000262: 
511B
000263: 122189	33879	1361	28830
000264: 
511B
000265: 122180	33878	1375	28852
000266: 
511B
000267: 122185	33874	1370	28856
000268: 
511B
000269: 122185	33876	1363	28855
000270: 
511B
000271: 122180	33871	1359	28850
000272: 
511B
000273: 122185	33871	1364	28861
000274: 
511B
000275: 122184	33876	1363	28842
000276: 
511B
000277: 122187	33870	1368	28845
000278: 
511B
000279: 122180	33876	1364	28842
000280: 
511B
000281: 122183	33880	1365	28860
000282: 
511B
000283: 122183	33883	1371	28849
000284: 
511B
000285: 122177	33876	1369	28863
000286: 
511B
000287: 122185	33881	1370	28856
000288: 
511B
000289: 122190	33880	1367	28850
000290: 
511B
000291: 122182	33878	1365	28847
000292: 
511B
000293: 122184	33877	1365	28847
000294: 
511B
000295: 122181	33873	1370	28841
000296: 
511B
000297: 122184	33881	1370	28846
000298: 
511B
000299: 122188	33878	1363	28854
000300: 
511B
000301: 122178	33873	1363	28838
000302: 
511B
000303: 122187	33879	1369	28842
000304: 
511B
000305: 122182	33876	1372	28840
000306: 
511B
000307: 122178	33880	1371	28837
000308: 
511B
000309: 122178	33874	1364	28857
000310: 
511B
000311: 122177	33873	1368	28857
000312: 
511B
000313: 122180	33881	1364	28842
000314: 
511B
000315: 122177	33873	1374	28845
000316: 
511B
000317: 122184	33877	1362	28835
000318: 
511B
000319: 122187	33878	1368	28854
000320: 
511B
000321: 122178	33879	1369	28838
000322: 
511B
000323: 122185	33874	1369	28848
000324: 
511B
000325: 122187	33878	1372	28838
000326: 
511B
000327: 122178	33878	1367	28835
000328: 
511B
000329: 122176	33880	1366	28834
000330: 
511B
000331: 122178	33871	1368	28843
000332: 
511B
000333: 122180	33871	1369	28861
000334: 
511B
000335: 122182	33871	1367	28838
000336: 
511B
000337: 122181	33878	1372	28845
000338: 
511B
000339: 122180	33872	1370	28847
000340: 
511B
000341: 122189	33869	1366	28838
000342: 
511B
000343: 122182	33868	1368	28834
000344: 
511B
000345: 122182	33878	1376	28848
000346: 
511B
000347: 122181	33881	1375	28836
000348: 
511B
000349: 122190	33875	1356	28839
000350: 
511B
000351: 122188	33879	1366	28838
000352: 
511B
000353: 122181	33876	1361	28839
000354: 
511B
000355: 122184	33874	1366	28850
000356: 
511B
000357: 122182	33874	1372	28852
000358: 
511B
000359: 122181	33877	1365	28836
000360: 
511B
000361: 122188	33869	1363	28838
000362: 
511B
000363: 122183	33879	1377	28845
000364: 
511B
000365: 122180	33868	1360	28836
000366: 
511B
000367: 122183	33870	1374	28851
000368: 
511B
000369: 122190	33882	1365	28853
000370: 
511B
000371: 122182	33869	1361	28847
000372: 
511B
000373: 122191	33873	1356	28837
000374: 
511B
000375: 122190	33875	1363	28855
000376: 
511B
000377: 122182	33873	1361	28849
000378: 
511B
000379: 122190	33875	1367	28850
000380: 
511B
000381: 122185	33872	1368	28851
000382: 
511B
000383: 122179	33867	1369	28843
000384: 
511B
000385: 122185	33875	1365	28847
000386: 
511B
000387: 122180	33868	1360	28850
000388: 
511B
000389: 122188	33868	1371	28855
000390: 
511B
000391: 122182	33868	1372	28855
000392: 
511B
000393: 122178	33868	1360	28861
000394: 
511B
000395: 122183	33874	1366	28846
000396: 
511B
000397: 122180	33869	1365	28844
000398: 
511B
000399: 122185	33871	1363	28838
000400: 
511B
000401: 122183	33875	1359	28848
000402: 
511B
000403: 122181	33871	1365	28835
000404: 
511B
000405: 122192	33871	1373	28848
000406: 
511B
000407: 122181	33873	1365	28849
000408: 
511B
000409: 122192	33872	1365	28853
000410: 
511B
000411: 122183	33875	1368	28847
000412: 
511B
000413: 122180	33874	1360	28839
000414: 
511B
000415: 122185	33877	1370	28840
000416: 
511B
000417: 122186	33872	1368	28855
000418: 
511B
000419: 122187	33884	1365	28843
000420: 
511B
000421: 122186	33876	1367	28839
000422: 
511B
000423: 122186	33874	1365	28847
000424: 
511B
000425: 122192	33875	1360	28834
000426: 
511B
000427: 122186	33877	1362	28839
000428: 
511B
000429: 122183	33875	1367	28834
000430: 
511B
000431: 122180	33876	1372	28845
000432: 
511B
000433: 122188	33875	1365	28845
000434: 
511B
000435: 122188	33880	1365	28843
000436: 
511B
000437: 122180	33872	1370	28840
000438: 
511B
000439: 122187	33878	1357	28837
000440: 
511B
000441: 122183	33876	1370	28843
000442: 
511B
000443: 122180	33872	1367	28843
000444: 
511B
000445: 122187	33880	1372	28845
000446: 
511B
000447: 122176	33867	1371	28840
000448: 
511B
000449: 122182	33872	1366	28854
000450: 
511B
000451: 122180	33869	1368	28862
000452: 
511B
000453: 122186	33870	1355	28846
000454: 
511B
000455: 122184	33875	1368	28835
000456: 
511B
000457: 122185	33880	1370	28846
000458: 
511B
000459: 122184	33875	1365	28830
000460: 
511B
000461: 122184	33861	1368	28861
000462: 
511B
000463: 122187	33867	1359	28845
000464: 
511B
000465: 122180	33867	1369	28847
000466: 
511B
000467: 122182	33873	1365	28844
000468: 
511B
000469: 122179	33865	1368	28835
000470: 
511B
000471: 122186	33867	1371	28843
000472: 
511B
000473: 122176	33867	1365	28850
000474: 
511B
000475: 122192	33867	1362	28837
000476: 
511B
000477: 122185	33862	1361	28840
000478: 
511B
000479: 122188	33860	1368	28835
000480: 
511B
000481: 122188	33862	1361	28853
000482: 
511B
000483: 122177	33863	1371	28846
000484: 
511B
000485: 122180	33868	1364	28839
000486: 
511B
000487: 122181	33868	1363	28841
000488: 
511B
000489: 122186	33860	1355	28850
000490: 
511B
000491: 122182	33860	1358	28840
000492: 
511B
000493: 122180	33856	1372	28847
000494: 
511B
000495: 122186	33862	1365	28835
000496: 
511B
000497: 122180	33859	1361	28852
000498: 
511B
000499: 122183	33864	1362	28850
000500: 
511B
000501: 122187	33858	1367	28847
000502: 
511B
000503: 122178	33859	1362	28855
000504: 
511B
000505: 122188	33862	1374	28843
000506: 
511B
000507: 122186	33856	1364	28856
000508: 
511B
000509: 122180	33862	1367	28835
000510: 
511B
000511: 122184	33863	1362	28834
000512: 
511B
000513: 122182	33864	1371	28847
000514: 
511B
000515: 122183	33862	1368	28851
000516: 
511B
000517: 122176	33854	1373	28842
000518: 
511B
000519: 122186	33861	1369	28859

VC ramp up,

000520: 
0C
000521: 122356	32893	349	459
000522: 
1C
000523: 122439	32871	335	5
000524: 
2C
000525: 122441	32882	341	141
000526: 
3C
000527: 122433	32890	351	354
000528: 
4C
000529: 122436	32900	357	560
000530: 
5C
000531: 122432	32900	356	561
000532: 
6C
000533: 122429	32909	361	786
000534: 
7C
000535: 122436	32923	368	980
000536: 
8C
000537: 122420	32947	365	1196
000538: 
9C
000539: 122431	32969	376	1416
000540: 
10C
000541: 122432	32961	375	1418
000542: 
11C
000543: 122417	32970	380	1705
000544: 
12C
000545: 122421	32989	385	1883
000546: 
13C
000547: 122415	32995	391	2085
000548: 
14C
000549: 122420	33000	396	2089
000550: 
15C
000551: 122413	33001	389	2293
000552: 
16C
000553: 122416	33008	407	2514
000554: 
.
.
.

`

**Comment by JosephEoff** [comment]
There is no "charging" time.  Before each trace, it measures the base current.  Because the base current is so low (only a few microamperes) it takes many measurements and averages to get an accurate measurements.

[Read my blog posts,](https://josepheoff.github.io/posts/iv-1-toc) if you'd like to see how I decided how things should work.

**Comment by xiaolaba** [comment]
thanks.
